# Thin entry script. Heavy logic moved to depth_anything_3.training.*
# Auto-generated by extract_training_modules.py

import os
import argparse
import torch
import numpy as np
import wandb
from depth_anything_3.api import DepthAnything3
from depth_anything_3.sparse_voxelizer import SparseVoxelizer
from depth_anything_3.model.voxel_gaussian_decoder import VoxelGaussianDecoder
from depth_anything_3.model.voxel_gaussian_decoder_v2 import VoxelGaussianDecoderV2
from depth_anything_3.model.sky_mlp import SkyMLP
import lpips
import lpips

# imports from training package
from depth_anything_3.training.utils import set_seed, ensure_dir, make_timestamped_output_dir, chunk_list, get_cpu_mem_stats, get_gpu_mem_stats
from depth_anything_3.training.wandb_utils import make_wandb_image_triplet_with_mask
from depth_anything_3.training.scene_discovery import discover_waymo_scenes, load_scene_name_list, filter_scenes_by_name, report_missing_scene_names
from depth_anything_3.training.checkpoint_io import save_debug_ply_pair, save_checkpoint
from depth_anything_3.training.train_step import train_one_group
from depth_anything_3.training.validation import safe_verify_scene_no_cache

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--image-path", type=str,
        default="None", help="Folder containing input jpg images")
    parser.add_argument(
        "--dataset-root",
        type=str,
        default="None",
        help="Dataset root containing scene folders, e.g. datasets/waymo/",
    )
    parser.add_argument(
        "--camera-name",
        type=str,
        default="FRONT",
        help="Camera subfolder inside each scene folder",
    )
    parser.add_argument("--output-dir", type=str, required=True)
    parser.add_argument("--model-id", type=str, default="depth-anything/DA3NESTED-GIANT-LARGE")
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--group-size", type=int, default=2)
    parser.add_argument("--steps-per-group", type=int, default=5)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--views-per-step", type=int, default=2)
    parser.add_argument("--render-chunk-size", type=int, default=2)
    parser.add_argument("--lambda-photo", type=float, default=1.0)
    parser.add_argument("--lambda-color", type=float, default=0.1)
    parser.add_argument("--val-every", type=int, default=5)
    parser.add_argument("--val-scene-names", nargs="*", default=[])
    parser.add_argument("--val-max-scenes", type=int, default=4)
    parser.add_argument("--val-view-indices", nargs="*", type=int, default=[0, 10, 20])
    parser.add_argument("--verify-render-chunk-size", type=int, default=2)

    parser.add_argument("--sequence-length", type=int, default=12)
    parser.add_argument("--sequence-stride", type=int, default=1)
    parser.add_argument(
        "--supervision-mode",
        type=str,
        default="even_input_mixed_supervision",
        choices=[
            "random_views",
            "even_input_mixed_supervision",
        ],
    )

    parser.add_argument(
        "--scene-list-file",
        type=str,
        default=None,
        help="Path to a txt file containing one scene name per line",
    )
    parser.add_argument(
        "--scene-filter-mode",
        type=str,
        default="restrict",
        choices=["restrict", "exclude"],
        help="How to apply --scene-list-file to discovered scenes",
    )
    parser.add_argument(
        "--train-only-scene-list",
        action="store_true",
        help="If set, apply scene-list filtering only to training scenes, not validation scenes",
    )

    # voxelizer params
    parser.add_argument("--voxel-size", type=float, default=0.4)
    parser.add_argument("--max-depth", type=float, default=50.0)
    parser.add_argument("--conf-percentile", type=float, default=40.0)
    parser.add_argument("--truncation-band", type=float, default=0.5)
    parser.add_argument("--feat-mode", type=str, default="last2_avg")
    parser.add_argument("--feat-dim-out", type=int, default=128)
    parser.add_argument("--neighbor-patch-radius", type=int, default=0,
                        help="Neighboring patch radius for voxel feature aggregation (0=center only, 1=3x3, 2=5x5)")
    parser.add_argument("--perview-conf", action="store_true",
                        help="Compute confidence threshold per view instead of globally")
    parser.add_argument("--voxel-size-dist-ref", type=float, default=0.0,
                        help=">0 enables distance-adaptive voxel size; vsize = voxel_size * max(1, d/ref)^exp")
    parser.add_argument("--voxel-size-exp", type=float, default=1.0,
                        help="Exponent for adaptive sizing: 1.0 = linear-with-distance, 2.0 ≈ inverse-depth-uniform")

    # Optional sky MLP head (directional sky color predictor)
    parser.add_argument("--use-sky-mlp", action="store_true",
                        help="Enable directional MLP sky color head")
    parser.add_argument("--sky-mlp-hidden-dim", type=int, default=64)
    parser.add_argument("--sky-mlp-num-freq", type=int, default=4,
                        help="Sinusoidal positional-encoding freq bands for ray direction")
    parser.add_argument("--sky-mlp-num-layers", type=int, default=3)
    parser.add_argument("--lambda-sky", type=float, default=1.0,
                        help="Weight for sky MLP L1 loss on sky-masked pixels")

    # depth + normal supervision (uses DA3 depth as GT)
    parser.add_argument("--lambda-depth", type=float, default=0.0,
                        help="Weight for L1 between rendered_depth and DA3 depth (non-sky pixels). 0 = off.")
    parser.add_argument("--lambda-normal", type=float, default=0.0,
                        help="Weight for normal-consistency loss (1 - cos(normal(rendered), normal(GT))). 0 = off.")

    # anisotropy regularizer (set 0 to allow naturally anisotropic Gaussians)
    parser.add_argument("--lambda-aniso", type=float, default=0.05,
                        help="Weight for anisotropy reg ((max_scale/mean_scale - 1)^2). Set 0 to allow flat/needle Gaussians for shape fitting.")

    # shape supervision: match Gaussian scales to local point distribution std (voxel_var_points)
    parser.add_argument("--lambda-shape", type=float, default=0.0,
                        help="Weight for log-ratio match between Gaussian scales and per-voxel point std. Encourages Gaussians to fit local surface geometry. 0 = off.")
    parser.add_argument("--lambda-normal-align", type=float, default=0.0,
                        help="Per-Gaussian normal alignment: rotate each Gaussian so its smallest-scale axis matches the per-anchor normal proxy (axis of min voxel variance). 0 = off.")
    parser.add_argument("--scale-clamp-mult", type=float, default=0.5,
                        help="Max Gaussian scale = scale_clamp_mult * voxel_size. Default 0.5 (i.e., 0.2m at voxel_size=0.4). Increase to 1.0 or 2.0 to allow larger Gaussians for shape fitting.")
    parser.add_argument("--scale-clamp-distance-ref", type=float, default=0.0,
                        help="Distance-adaptive scale clamp. 0 = static clamp. >0 = clamp scales with (1 + dist/ref) so far Gaussians can be larger (matches 1/depth image footprint). E.g., 10.0 means 5x clamp at 50m anchor distance. Recommended: 10-20 for driving scenes.")
    parser.add_argument("--scale-init-mult", type=float, default=0.1,
                        help="Initial Gaussian scale = exp(scale_raw) * scale_init_mult * voxel_size. Default 0.1 (init ~0.04m at voxel=0.4). Increase to start Gaussians larger (e.g., 1.2 to start at ~0.48m for better coverage early in training).")

    # sky mask
    parser.add_argument(
        "--cache-root",
        type=str,
        default="output_train_voxel_decoder/cache",
        help="Fixed cache root for precomputed scene cache such as sky masks",
    )

    # decoder params
    parser.add_argument("--hidden-dim", type=int, default=256)
    parser.add_argument("--num-gaussians", type=int, default=4)
    parser.add_argument("--decoder-version", type=str, default="v1", choices=["v1", "v2"],
                        help="v1 = single shared decoder; v2 = split GeometryHead + AppearanceHead with pixel-aligned appearance feature")
    parser.add_argument("--keep-pixel-features", action="store_true",
                        help="Aggregate full-dim DINO per voxel (required for v2)")

    # save ckpt
    parser.add_argument("--save-every", type=int, default=1)
    parser.add_argument("--keep-last-k", type=int, default=5)
    parser.add_argument("--resume", type=str, default=None)

    # wandb params
    parser.add_argument("--use-wandb", action="store_true")
    parser.add_argument("--wandb-project", type=str, default="voxel-anchored-3dgs")
    parser.add_argument("--wandb-entity", type=str, default=None)
    parser.add_argument("--wandb-run-name", type=str, default=None)
    parser.add_argument("--wandb-log-train-images-every", type=int, default=1)
    parser.add_argument("--wandb-log-val-images", action="store_true")
    parser.add_argument("--wandb-watch-model", action="store_true")

    args = parser.parse_args()

    args.output_dir = make_timestamped_output_dir(args.output_dir)
    print(f"[INFO] Output directory: {args.output_dir}")

    set_seed(42)
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    ensure_dir(args.output_dir)

    # wandb setup
    run = None
    if args.use_wandb:
        run = wandb.init(
            project=args.wandb_project,
            entity=args.wandb_entity,
            name=args.wandb_run_name,
            config=vars(args),
            dir=args.output_dir,
        )

        if args.wandb_watch_model:
            wandb.watch(decoder if "decoder" in locals() else None, log="all", log_freq=100)

    scenes = discover_waymo_scenes(
    dataset_root=args.dataset_root,
    camera_name=args.camera_name,
    )
    print(f"[INFO] Found {len(scenes)} scenes before filtering")

    scene_list_names = []
    if args.scene_list_file is not None:
        scene_list_names = load_scene_name_list(args.scene_list_file)
        print(f"[INFO] Loaded {len(scene_list_names)} scene names from {args.scene_list_file}")

    # split first
    if len(args.val_scene_names) > 0:
        val_scene_names = set(args.val_scene_names)
        val_scenes = [s for s in scenes if s["scene_name"] in val_scene_names]
        train_scenes = [s for s in scenes if s["scene_name"] not in val_scene_names]
    else:
        val_scenes = scenes[-args.val_max_scenes:]
        train_scenes = scenes[:-args.val_max_scenes] if len(scenes) > args.val_max_scenes else scenes

    # then filter by scene list
    if len(scene_list_names) > 0:
        if args.train_only_scene_list:
            train_scenes = filter_scenes_by_name(
                train_scenes,
                scene_list_names,
                mode=args.scene_filter_mode,
            )
        else:
            train_scenes = filter_scenes_by_name(
                train_scenes,
                scene_list_names,
                mode=args.scene_filter_mode,
            )
            val_scenes = filter_scenes_by_name(
                val_scenes,
                scene_list_names,
                mode=args.scene_filter_mode,
            )

    print(f"[INFO] Final train scenes: {len(train_scenes)}")
    print(f"[INFO] Final val scenes: {len(val_scenes)}")

    if len(train_scenes) == 0:
        raise RuntimeError("No training scenes left after filtering.")

    if len(val_scenes) == 0:
        print("[WARN] No validation scenes left after filtering.")

    report_missing_scene_names(scenes, scene_list_names)
    # scenes = scenes[:1]
    # val_scenes = scenes[:1]

    model = DepthAnything3.from_pretrained(args.model_id).to(device)
    model.eval()
    for p in model.parameters():
        p.requires_grad = False

    keep_pixel_features = args.keep_pixel_features or args.decoder_version == "v2"
    if args.decoder_version == "v2" and not args.keep_pixel_features:
        print("[INFO] --decoder-version v2 implies --keep-pixel-features; enabling automatically")

    voxelizer = SparseVoxelizer(
        max_depth=args.max_depth,
        voxel_size=args.voxel_size,
        conf_percentile=args.conf_percentile,
        truncation_band=args.truncation_band,
        feat_mode=args.feat_mode,
        neighbor_patch_radius=args.neighbor_patch_radius,
        perview_conf=args.perview_conf,
        feat_dim_out=args.feat_dim_out,
        voxel_size_dist_ref=args.voxel_size_dist_ref,
        voxel_size_exp=args.voxel_size_exp,
        keep_pixel_features=keep_pixel_features,
    )

    # 用第一個 scene warmup，拿 dino_dim
    first_scene = scenes[0]
    with torch.no_grad():
        pred = model.inference(
            first_scene["image_paths"],
            export_dir=args.output_dir,
            export_format="none",
        )
        voxel_dict = voxelizer.voxelize_prediction(pred)

    if voxel_dict["voxel_features"] is None:
        raise RuntimeError("voxel_features is None.")

    dino_dim = voxel_dict["voxel_features"].shape[1]

    if args.decoder_version == "v2":
        if voxel_dict.get("voxel_pixel_features", None) is None:
            raise RuntimeError("v2 decoder needs voxel_pixel_features; check --keep-pixel-features wiring")
        pixel_dim = voxel_dict["voxel_pixel_features"].shape[1]
        decoder = VoxelGaussianDecoderV2(
            dino_dim=dino_dim,
            pixel_dim=pixel_dim,
            hidden_dim=args.hidden_dim,
            num_gaussians=args.num_gaussians,
            voxel_size=args.voxel_size,
            scale_clamp_mult=args.scale_clamp_mult,
            scale_clamp_distance_ref=args.scale_clamp_distance_ref,
            scale_init_mult=args.scale_init_mult,
        ).to(device)
    else:
        decoder = VoxelGaussianDecoder(
            dino_dim=dino_dim,
            hidden_dim=args.hidden_dim,
            num_gaussians=args.num_gaussians,
            voxel_size=args.voxel_size,
            scale_clamp_mult=args.scale_clamp_mult,
            scale_clamp_distance_ref=args.scale_clamp_distance_ref,
            scale_init_mult=args.scale_init_mult,
        ).to(device)

    # Free warmup voxel_dict before training begins — the pred + voxel_dict here
    # were only used to probe dino_dim/pixel_dim and would otherwise pin ~1+ GB
    # of GPU memory through the rest of main() (matters most for v2 where the
    # full-dim pixel feature tensor is the dominant cost).
    del voxel_dict, pred
    torch.cuda.empty_cache()

    # Optional sky MLP (directional sky color predictor)
    sky_mlp = None
    if args.use_sky_mlp:
        sky_mlp = SkyMLP(
            global_feat_dim=args.feat_dim_out,
            hidden_dim=args.sky_mlp_hidden_dim,
            num_freq=args.sky_mlp_num_freq,
            num_layers=args.sky_mlp_num_layers,
        ).to(device)
        print(f"[INFO] SkyMLP enabled: hidden={args.sky_mlp_hidden_dim} "
              f"num_freq={args.sky_mlp_num_freq} num_layers={args.sky_mlp_num_layers} "
              f"lambda_sky={args.lambda_sky}")

    if sky_mlp is not None:
        optimizer = torch.optim.Adam(
            list(decoder.parameters()) + list(sky_mlp.parameters()),
            lr=args.lr,
        )
    else:
        optimizer = torch.optim.Adam(decoder.parameters(), lr=args.lr)

    lpips_fn = lpips.LPIPS(net="alex").cpu()
    lpips_fn.eval()
    for p in lpips_fn.parameters():
        p.requires_grad_(False)

    start_epoch = 1

    if args.resume is not None:
        print(f"[INFO] Loading checkpoint from {args.resume}")
        ckpt = torch.load(args.resume, map_location=device)

        decoder.load_state_dict(ckpt["decoder"])
        optimizer.load_state_dict(ckpt["optimizer"])

        start_epoch = ckpt["epoch"] + 1
        print(f"[INFO] Resume from epoch {start_epoch}")

    # scene_groups = chunk_list(scenes, args.group_size)
    scene_groups = chunk_list(train_scenes, args.group_size)

    if args.use_wandb and args.wandb_watch_model:
        wandb.watch(decoder, log="all", log_freq=100)

    best_val = float("inf")

    global_step = 0
    for epoch in range(start_epoch, args.epochs + 1):
        last_train_log = None
        epoch_logs = []
        print(f"\n[INFO] Epoch {epoch:04d}/{args.epochs}")
        np.random.shuffle(scene_groups)

        for group_idx, group in enumerate(scene_groups):
            print(f"[INFO] Loading group {group_idx+1}/{len(scene_groups)} with {len(group)} scenes")

            logs = train_one_group(
                decoder=decoder,
                optimizer=optimizer,
                group_scenes=group,
                model=model,
                voxelizer=voxelizer,
                cache_root=args.cache_root,
                views_per_step=args.views_per_step,
                steps_per_group=args.steps_per_group,
                device=device,
                sequence_length=args.sequence_length,
                supervision_mode=args.supervision_mode,
                lpips_fn=lpips_fn,
                sky_mlp=sky_mlp,
                lambda_sky=args.lambda_sky,
                lambda_depth=args.lambda_depth,
                lambda_normal=args.lambda_normal,
                lambda_aniso=args.lambda_aniso,
                lambda_shape=args.lambda_shape,
                lambda_normal_align=args.lambda_normal_align,
            )

            if len(logs) == 0:
                print("[WARN] No valid logs in this group.")
                continue
            if len(logs) > 0:
                last_train_log = logs[-1]
                epoch_logs.extend(logs)

            avg_total = np.mean([x["total"] for x in logs])
            print(f"[INFO] Group {group_idx+1} avg_total={avg_total:.6f}")
            if args.use_wandb:
                for local_step, log_item in enumerate(logs):
                    global_step += 1

                    wandb_log = {
                        "train/epoch": epoch,
                        "train/group_idx": group_idx + 1,
                        "train/global_step": global_step,
                        "train/loss_total": log_item["total"],
                    }

                    delta_color_stats = log_item.get("delta_color_stats", None)
                    if delta_color_stats is not None:
                        wandb_log["train/delta_color_abs_mean"] = delta_color_stats["abs_mean"]

                    # save all loss in log_item that are not None
                    for k, v in log_item["losses"].items():
                        # print(f"[DEBUG] loss {k} = {v}")
                        if v is not None:
                            wandb_log[f"train/loss_{k}"] = v
                    # if log_item["photo"] is not None:
                    #     wandb_log["train/loss_photo"] = log_item["photo"]
                    # if log_item["offset_reg"] is not None:
                    #     wandb_log["train/loss_offset_reg"] = log_item["offset_reg"]

                    wandb_log.update({
                        f"train/{k}": v for k, v in log_item.get("scene_stats", {}).items()
                    })

                    wandb_log.update({
                        f"train/memory/{k}": v for k, v in get_cpu_mem_stats().items()
                    })
                    wandb_log.update({
                        f"train/memory/{k}": v for k, v in get_gpu_mem_stats(device).items()
                    })
                    sampling_stats = log_item.get("sampling_stats", None)
                    if sampling_stats is not None:
                        wandb_log["train/num_seen_supervision"] = sampling_stats["num_seen"]
                        wandb_log["train/num_novel_supervision"] = sampling_stats["num_novel"]

                    if global_step % args.wandb_log_train_images_every == 0:
                        # print log_item["rendered_rgb"].shape, log_item["gt_rgb"].shape
                        # print(f"[DEBUG] log_item['rendered_rgb'] shape={log_item['rendered_rgb'].shape}, dtype={log_item['rendered_rgb'].dtype}, device={log_item['rendered_rgb'].device}")
                        # print(f"[DEBUG] log_item['gt_rgb'] shape={log_item['gt_rgb'].shape}, dtype={log_item['gt_rgb'].dtype}, device={log_item['gt_rgb'].device}")
                        # pred0 = log_item["rendered_rgb"][0].detach().cpu()
                        pred0 = log_item["rendered_rgb"][0].detach().cpu()
                        gt0 = log_item["gt_rgb"][0].detach().cpu()
                        # print(f"[DEBUG] log_item['sky_mask'] shape={log_item['sky_mask'].shape}, dtype={log_item['sky_mask'].dtype}, device={log_item['sky_mask'].device}")
                        mask0 = log_item["sky_mask"].detach().cpu()
                        imgs = make_wandb_image_triplet_with_mask(
                            pred=pred0,
                            gt=gt0,
                            mask=mask0,
                            caption=f"train step={global_step} scene={log_item['scene_name']}",
                        )
                        wandb_log["train/render_samples"] = imgs

                        # save debug PLY pair for this render_samples step
                        if log_item.get("flat_scene_to_save") is not None:
                            save_debug_ply_pair(
                                flat_scene=log_item["flat_scene_to_save"],
                                voxel_mean_points=log_item.get("voxel_mean_points"),
                                output_dir=args.output_dir,
                                global_step=global_step,
                                scene_name=log_item["scene_name"],
                                keep_last_k=10,
                            )

                    wandb.log(wandb_log, step=global_step)

            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        if epoch % args.save_every == 0:
            save_checkpoint(
                decoder=decoder,
                optimizer=optimizer,
                epoch=epoch,
                output_dir=args.output_dir,
                keep_last_k=args.keep_last_k,
            )
        
        if epoch % args.val_every == 0:
            val_l1_list = []
            print(f"\n[INFO] Validation for epoch {epoch:04d} on {len(val_scenes)} scenes")
            for scene in val_scenes:
                verify_out = safe_verify_scene_no_cache(
                    decoder=decoder,
                    model=model,
                    voxelizer=voxelizer,
                    image_paths=scene["image_paths"],
                    scene_name=scene["scene_name"],
                    output_dir=args.output_dir,
                    cache_root=args.cache_root,
                    epoch=epoch,
                    device=device,
                )
                if verify_out["ok"]:
                    val_info = verify_out["result"]
                    # 正常 log / save
                    val_l1_list.append(val_info["l1"])
                else:
                    print(f"[WARN] skip this verification because of error: {verify_out['error']}")
                    continue

                if args.use_wandb:
                    val_log = {
                        "val/epoch": epoch,
                        "val/l1": val_info["l1"],
                        "val/num_voxels": val_info["num_voxels"],
                        "val/num_gaussians": val_info["num_gaussians"],
                        **{f"val/memory/{k}": v for k, v in get_cpu_mem_stats().items()},
                        **{f"val/memory/{k}": v for k, v in get_gpu_mem_stats(device).items()},
                    }

                    if args.wandb_log_val_images:
                        # print pred0, gt0, mask0
                        # print(f"[DEBUG] val_info['pred_rgb'] shape={val_info['pred_rgb'].shape}, dtype={val_info['pred_rgb'].dtype}, device={val_info['pred_rgb'].device}")
                        # print(f"[DEBUG] val_info['gt_rgb'] shape={val_info['gt_rgb'].shape}, dtype={val_info['gt_rgb'].dtype}, device={val_info['gt_rgb'].device}")
                        # print(f"[DEBUG] val_info['sky_mask'] shape={val_info['sky_mask'].shape}, dtype={val_info['sky_mask'].dtype}, device={val_info['sky_mask'].device}")

                        pred0 = val_info["pred_rgb"][0]
                        gt0 = val_info["gt_rgb"][0]
                        mask0 = val_info["sky_mask"][0]
                        val_log[f"val/{val_info['scene_name']}_samples"] = make_wandb_image_triplet_with_mask(
                            pred=pred0,
                            gt=gt0,
                            mask=mask0,
                            caption=f"val epoch={epoch} scene={val_info['scene_name']}",
                        )

                    wandb.log(val_log, step=global_step)
            if len(val_l1_list) > 0:
                mean_val = np.mean(val_l1_list)

                if mean_val < best_val:
                    best_val = mean_val

                    torch.save({
                        "epoch": epoch,
                        "decoder": decoder.state_dict(),
                        "optimizer": optimizer.state_dict(),
                        "best_val": best_val,
                    }, os.path.join(args.output_dir, "best.pth"))

                    print(f"[INFO] Saved BEST checkpoint (val={best_val:.6f})")
            
            if args.use_wandb and len(val_l1_list) > 0:
                wandb.log({
                    "val/epoch_mean_l1": float(np.mean(val_l1_list)),
                    "val/epoch": epoch,
                }, step=global_step)

if __name__ == "__main__":
    main()